function applyTheme(){document.documentElement.dataset.theme=STATE.settings.theme==='dark'?'dark':'';document.body.style.fontSize=STATE.settings.font_size==='large'?'18px':STATE.settings.font_size==='small'?'14px':'16px'}
// Cloze-style hint: keep a couple of anchor words visible and mask the middle.
const _practiceRender=PracticePage.render.bind(PracticePage), _showResult=PracticePage.showResult.bind(PracticePage);
PracticePage.render=function(){STATE.answerShown=false;_practiceRender();const item=STATE.sequence[STATE.index];const input=document.getElementById('answer');if(!item||!input)return;const expanded=item.en.replace(/\bI'm\b/gi,'I am').replace(/\bI've\b/gi,'I have').replace(/\bI'll\b/gi,'I will').replace(/[.!?]+$/,'');const words=expanded.split(/\s+/);if(words.length<4)return;const visible=words.map((w,i)=>{const edge=i<2||i>=words.length-2;const middleHint=i>=2&&i<words.length-2&&i%3===2;return edge||middleHint?w:'_'});const hint=document.createElement('div');hint.className='cloze-hint';hint.textContent=visible.join('　');input.parentNode.insertBefore(hint,input)};
PracticePage.showResult=function(ok,answer,notes=''){STATE.answerShown=true;_showResult(ok,answer,notes)};
function toggleAnswer(){const hint=document.querySelector('.cloze-hint'),item=STATE.sequence[STATE.index];if(!hint||!item)return;if(STATE.answerShown){hint.textContent=hint.dataset.masked||hint.textContent;STATE.answerShown=false}else{const masked=hint.textContent;hint.dataset.masked=masked;const full=item.en.replace(/\bI'm\b/gi,'I am').replace(/\bI've\b/gi,'I have').replace(/\bI'll\b/gi,'I will').replace(/[.!?]+$/,'');const maskParts=masked.split(/(\s+)/),fullParts=full.split(/(\s+)/);let wi=0;hint.innerHTML=fullParts.map(part=>{if(/^\s+$/.test(part))return part;const mask=maskParts.filter(x=>!/^\s+$/.test(x))[wi++];return mask==='_'?`<span class="revealed-word">${part}</span>`:part}).join('');STATE.answerShown=true}}
async function boot(){try{await API.ready;const b=await API.call('bootstrap');STATE.libraries=b.libraries;STATE.wordlists=b.wordlists||[];STATE.readings=b.readings||[];STATE.settings=b.settings;applyTheme();LibraryPage.render();document.getElementById('words-btn').onclick=()=>WordPage.showLibraries();document.getElementById('readings-btn').onclick=()=>ReadingPage.showLibraries();document.getElementById('settings-btn').onclick=()=>SettingsPage.show();document.getElementById('back').onclick=()=>ReadingPage.active?ReadingPage.back():(WordPage.active?WordPage.back():LibraryPage.render());document.getElementById('favorites-btn').onclick=()=>{WordPage.active=false;ReadingPage.active=false;PracticePage.open('', 'start','favorites')};const close=document.getElementById('close-btn');if(API.mode==='static')close.hidden=true;else close.onclick=()=>Dialog.show('关闭应用','确定关闭英语学习吗？',[{label:'确定关闭',action:()=>API.call('shutdown')},{label:'取消',action:()=>Dialog.close()}])}catch(error){document.getElementById('view').innerHTML=`<section class="content empty"><h1>题库加载失败</h1><p>${error.message||error}</p><p>请刷新页面后重试。</p></section>`;console.error(error)}}
document.addEventListener('keydown',e=>{if(ReadingPage.handleKey(e))return;if(WordPage.handleKey(e))return;if(e.key==='Escape')Dialog.close();if(e.ctrlKey&&e.key==='ArrowLeft'){e.preventDefault();PracticePage.move(-1)}if(e.ctrlKey&&e.key==='ArrowRight'){e.preventDefault();PracticePage.move(1)}if(e.ctrlKey&&e.key.toLowerCase()==='d'){e.preventDefault();document.getElementById('fav')?.click()}if(e.ctrlKey&&e.key.toLowerCase()==='l'){e.preventDefault();document.getElementById('speak')?.click()}if(e.ctrlKey&&e.key.toLowerCase()==='h'){e.preventDefault();toggleAnswer()}});boot();
setTimeout(()=>{const f=document.querySelector('footer');if(f)f.textContent='Enter：提交答案 / 下一题　·　Ctrl + ←：上一题　·　Ctrl + →：下一题　·　Ctrl + D：收藏/取消收藏　·　Ctrl + L：朗读英文　·　Ctrl + H：查看/隐藏答案　·　Esc：关闭弹窗'},500);
